version: '2'
services:
  jhipstersampleapplication5-app:
    image: jhipstersampleapplication5
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersampleapplication5-mysql:3306/jhipstersampleapplication5?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://jhipstersampleapplication5-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jhipstersampleapplication5-elasticsearch:9200
    ports:
      - 8080:8080
  jhipstersampleapplication5-mysql:
    extends:
      file: mysql.yml
      service: jhipstersampleapplication5-mysql
  jhipstersampleapplication5-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jhipstersampleapplication5-elasticsearch
